//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoDigital.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autorizacao
    {
        public int IdAutorizacao { get; set; }
        public int IdPessoaUsuario { get; set; }
        public int IdDocumento { get; set; }
        public System.DateTime DataInicio { get; set; }
        public System.DateTime DataFim { get; set; }
        public int IdTipoAutorizacao { get; set; }
    
        public virtual Documento Documento { get; set; }
        public virtual TipoAutorizacao TipoAutorizacao { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
