//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoDigital.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cidade
    {
        public Cidade()
        {
            this.Endereco = new HashSet<Endereco>();
        }
    
        public int IdCidade { get; set; }
        public string NomeCidade { get; set; }
        public string UF { get; set; }
    
        public virtual UnidadeFederativa UnidadeFederativa { get; set; }
        public virtual ICollection<Endereco> Endereco { get; set; }
    }
}
