//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoDigital.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public Documento()
        {
            this.Autorizacao = new HashSet<Autorizacao>();
        }
    
        public int IdDocumento { get; set; }
        public int IdTipoDocumento { get; set; }
        public int IdUnidade { get; set; }
        public int IdPessoa { get; set; }
        public int IdPessoaUsuario { get; set; }
        public string NomeDocumento { get; set; }
        public byte[] ArquivoBlob { get; set; }
        public string Arquivo { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public string Observacao { get; set; }
    
        public virtual ICollection<Autorizacao> Autorizacao { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual Unidade Unidade { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
