//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoDigital.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endereco
    {
        public Endereco()
        {
            this.Unidade = new HashSet<Unidade>();
        }
    
        public int IdEndereco { get; set; }
        public string Logradouro { get; set; }
        public string Complemento { get; set; }
        public string Numero { get; set; }
        public string CEP { get; set; }
        public string Bairro { get; set; }
        public int IdCidade { get; set; }
        public int IdPessoa { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual ICollection<Unidade> Unidade { get; set; }
    }
}
