//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoDigital.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public Pessoa()
        {
            this.Documento = new HashSet<Documento>();
            this.Endereco = new HashSet<Endereco>();
        }
    
        public int IdPessoa { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public string Observacao { get; set; }
        public int IdTipoPessoa { get; set; }
        public string CPFCNPJ { get; set; }
    
        public virtual ICollection<Documento> Documento { get; set; }
        public virtual ICollection<Endereco> Endereco { get; set; }
        public virtual TipoPessoa TipoPessoa { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
