//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoDigital.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoAutorizacao
    {
        public TipoAutorizacao()
        {
            this.Autorizacao = new HashSet<Autorizacao>();
        }
    
        public int IdTipoAutorizacao { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<Autorizacao> Autorizacao { get; set; }
    }
}
