//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoDigital.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadeFederativa
    {
        public UnidadeFederativa()
        {
            this.Cidade = new HashSet<Cidade>();
        }
    
        public string UF { get; set; }
        public string NomeEstado { get; set; }
    
        public virtual ICollection<Cidade> Cidade { get; set; }
    }
}
