//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoDigital.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Autorizacao = new HashSet<Autorizacao>();
            this.Documento = new HashSet<Documento>();
        }
    
        public int IdPessoaUsuario { get; set; }
        public int IdUnidade { get; set; }
        public int IdTipoUsuario { get; set; }
        public string Senha { get; set; }
        public string Login { get; set; }
    
        public virtual ICollection<Autorizacao> Autorizacao { get; set; }
        public virtual ICollection<Documento> Documento { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
        public virtual Unidade Unidade { get; set; }
    }
}
